from Database.Types import DbKeywordWeight
from typing import TypedDict


class LLMKeywordsTopicResponseFormat(TypedDict):
    """
    This module defines the TypedDict for the keywords and topic response format of the LLM model.

    Attributes:
        response (str): The response generated by the LLM model.
        score (float): The score of the response generated by the LLM model.
    """

    keywords: list[str]
    topic: str


class LLMCategoryRequestFormat(TypedDict):
    """
    This module defines the TypedDict for the category request format of the LLM model.

    Attributes:
        keyword (list[DbKeywordWeight]): The list of keyword weights.
        category_number (int): The number of categories to be generated.
    """

    keyword: list[DbKeywordWeight]
    category_number: int
