from typing import TypedDict


class LLMResponseFormat(TypedDict):
    """
    This module defines the TypedDict for the response format of the LLM model.

    Attributes:
        response (str): The response generated by the LLM model.
        score (float): The score of the response generated by the LLM model.
    """

    keywords: list[str]
    topic: str
