from Database.Types import DbWeightedCategory, DbWeightedKeyword
from typing import TypedDict


class LLMKeywordsTopicResponseFormat(TypedDict):
    """
    This module defines the TypedDict for the keywords and topic response format of the LLM model.

    Attributes:
        keywords (list[str]): The list of keywords generated by the model.
        topic (str): The topic generated by the model.
    """

    keywords: list[str]
    topic: str


class LLMCategoryRequestFormat(TypedDict):
    """
    This module defines the TypedDict for the category request format of the LLM model.

    Attributes:
        weighted_objects (list[DbWeightedKeyword] | list[DbWeightedCategory]): The weighted objects to be categorized.
        category_number (int): The number of categories to be generated.
    """

    weighted_objects: list[DbWeightedKeyword] | list[DbWeightedCategory]
    category_number: int
